# Generated by Django 3.2.7 on 2021-09-14 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_atencion', models.CharField(max_length=20, null=True)),
                ('hora_final_atencion', models.CharField(max_length=20, null=True)),
                ('empresa', models.CharField(max_length=50, null=True)),
                ('ciudad', models.CharField(max_length=50, null=True)),
                ('asunto', models.CharField(max_length=70, null=True)),
                ('respuesta', models.CharField(max_length=70, null=True)),
                ('fecha_solicitud', models.DateField()),
            ],
        ),
    ]
